import fs from 'fs';
const sec = (s) => { for (const l of s.split('\n')) fs.appendFileSync('src/App.tsx', l + '\n', 'utf-8'); };
fs.writeFileSync('src/App.tsx', '', 'utf-8');
sec(`import { useState, useMemo } from 'react'`);
sec(`import { useEffect } from 'react'`);
sec(`import { fetchGenres, fetchDiscover, fetchTrending, fetchMovieDetail, tmdbImgUrl, tmdbToMovieMinimal, enrichMovieWithDetail } from './api/tmdb'`)
sec(`import quotes from './data/quotes.json'`);
sec(``);
sec(`type WatchStatus = 'none' | 'want' | 'watched'`);
sec(``);
sec(`interface Movie {`);
sec(`  id: number`);
sec(`  title: string`);
sec(`  titleCN: string`);
sec(`  year: number`);
sec(`  director: string`);
sec(`  rating: number`);
sec(`  genres: string[]`);
sec(`  duration: number`);
sec(`  description: string`);
sec(`  photo: string`);
sec(`  backdrop: string`);
sec(`}`);
sec(``);
sec(`interface Quote {`);
sec(`  text: string`);
sec(`  movie: string`);
sec(`  year: number`);
sec(`}`);
sec(``);
sec(`const QUOTES: Quote[] = quotes;`const QUOTES: Quote[] = quotes`  { text: "Fear can hold you prisoner. Hope can set you free.", movie: "The Shawshank Redemption", year: 1994 },`);
sec(`  { text: "Life is like a box of chocolates. You never know what you're gonna get.", movie: "Forrest Gump", year: 1994 },`);
sec(`  { text: "We look up at the stars not for answers, but for beauty.", movie: "Interstellar", year: 2014 },`);
sec(`  { text: "You jump, I jump.", movie: "Titanic", year: 1997 },`);
sec(`  { text: "Even the smallest person can change the course of the future.", movie: "The Lord of the Rings", year: 2003 },`);
sec(`  { text: "We buy things we don't need with money we don't have.", movie: "Fight Club", year: 1999 },`);
sec(`  { text: "A dream is real as long as you are in it.", movie: "Inception", year: 2010 },`);
sec(`  { text: "Why so serious?", movie: "The Dark Knight", year: 2008 },`);
sec(`  { text: "Game rule: never cry no matter what.", movie: "Life is Beautiful", year: 1997 },`);
sec(`  { text: "Some things become different once spoken.", movie: "Drive My Car", year: 2021 },`);
sec(`];`);
sec(``);
sec(`const imgUrl = (path: string, w: number, h?: number) =>`);
sec(`  path ? \`https://image.tmdb.org/t/p/w\${w}\${path}\` : ''`);
sec(``);
sec(`function getDailyPicks(movies: Movie[]): Movie[] {`);
sec(`  const d = new Date()`);
sec(`  const seed = d.getFullYear() * 10000 + (d.getMonth() + 1) * 100 + d.getDate()`);
sec(`  if (movies.length === 0) return []`);
sec(`  const picks: Movie[] = []`);
sec(`  const used = new Set<number>()`);
sec(`  let s = seed >>> 0`);
sec(`  for (let i = 0; picks.length < Math.min(5, movies.length) && i < 1000; i++) {`);
sec(`    s = (Math.imul(s ^ (s >>> 16), 0x45d9f3b) >>> 0)`);
sec(`    s = (Math.imul(s ^ (s >>> 16), 0x45d9f3b) >>> 0)`);
sec(`    const idx = s % movies.length`);
sec(`    if (!used.has(idx)) { used.add(idx); picks.push(movies[idx]) }`);
sec(`  }`);
sec(`  return picks`);
sec(`}`);
sec(``);
sec(`function getDailyQuote(): Quote {`);
sec(`  const d = new Date(); return QUOTES[d.getDate() % QUOTES.length]`);
sec(`}`);
sec(``);
sec(`function getTodayString(): string {`);
sec(`  const d = new Date()`);
sec(`  const days = ['日', '一', '二', '三', '四', '五', '六']`);
sec(`  return \`\${d.getFullYear()}年\${d.getMonth() + 1}月\${d.getDate()}日 · 星期\${days[d.getDay()]}\``);
sec(`}`);
sec(``);
sec(`function GenreTag({ label }: { label: string }) {`);
sec(`  return (`);
sec(`    <span style={{ padding: '2px 8px', borderRadius: '4px', fontSize: '10px', fontWeight: 600, letterSpacing: '0.04em', background: 'rgba(201,168,108,0.1)', color: '#c9a86c', border: '1px solid rgba(201,168,108,0.18)', whiteSpace: 'nowrap' }}>{label}</span>`);
sec(`  )`);
sec(`}`);
sec(``);
sec(`function ActionButtons({ id, status, onToggle, compact = false }: { id: number; status: WatchStatus; onToggle: (id: number, t: Exclude<WatchStatus, 'none'>) => void; compact?: boolean }) {`);
sec(`  const base: React.CSSProperties = { borderRadius: compact ? '6px' : '20px', fontSize: compact ? '11px' : '12px', fontWeight: 500, cursor: 'pointer', transition: 'all 0.18s', fontFamily: "'DM Sans', system-ui, sans-serif" }`);
sec(`  const wantActive = status === 'want'`);
sec(`  const watchedActive = status === 'watched'`);
sec(`  return (`);
sec(`    <div style={{ display: 'flex', gap: '8px' }}>`);
sec(`      <button onClick={e => { e.stopPropagation(); onToggle(id, 'want') }} style={{ ...base, padding: compact ? '6px 0' : '6px 14px', flex: compact ? 1 : undefined, border: wantActive ? '1px solid #c9a86c' : '1px solid rgba(255,255,255,0.12)', background: wantActive ? 'rgba(201,168,108,0.14)' : 'rgba(255,255,255,0.04)', color: wantActive ? '#c9a86c' : 'rgba(255,255,255,0.5)' }}>{wantActive ? '★ 想看' : '☆ 想看'}</button>`);
sec(`      <button onClick={e => { e.stopPropagation(); onToggle(id, 'watched') }} style={{ ...base, padding: compact ? '6px 0' : '6px 14px', flex: compact ? 1 : undefined, border: watchedActive ? '1px solid #c9a86c' : '1px solid rgba(255,255,255,0.12)', background: watchedActive ? 'rgba(201,168,108,0.14)' : 'rgba(255,255,255,0.04)', color: watchedActive ? '#c9a86c' : 'rgba(255,255,255,0.5)' }}>{watchedActive ? '● 看过' : '○ 看过'}</button>`);
sec(`    </div>`);
sec(`  )`);
sec(`}`);
sec(``);
sec(`function FeaturedCard({ movie, status, onToggle, onClick }: { movie: Movie; status: WatchStatus; onToggle: (id: number, t: Exclude<WatchStatus, 'none'>) => void; onClick: () => void }) {`);
sec(`  return (`);
sec(`    <div onClick={onClick} style={{ position: 'relative', borderRadius: '12px', overflow: 'hidden', cursor: 'pointer', marginBottom: '14px', minHeight: 'clamp(220px, 36vw, 400px)', background: '#111113' }}>`);
sec(`      <img src={imgUrl(movie.backdrop || movie.photo, 1000)} alt={movie.titleCN} style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'cover', objectPosition: 'center 30%' }} />`);
sec(`      <div style={{ position: 'absolute', inset: 0, background: 'linear-gradient(to top, rgba(10,10,12,0.95) 20%, rgba(10,10,12,0.2) 60%, transparent 80%)' }} />`);
sec(`      <div style={{ position: 'absolute', bottom: 0, left: 0, right: 0, padding: '32px', zIndex: 1 }}>`);
sec(`        <div style={{ display: 'flex', gap: '6px', marginBottom: '10px', flexWrap: 'wrap' }}>{movie.genres.slice(0, 3).map(g => <GenreTag key={g} label={g} />)}</div>`);
sec(`        <h2 style={{ fontFamily: "'Playfair Display', serif", fontSize: 'clamp(20px, 3.4vw, 32px)', fontWeight: 700, color: '#f0ece3', lineHeight: 1.15, letterSpacing: '-0.02em', marginBottom: '4px' }}>{movie.titleCN}</h2>`);
sec(`        <p style={{ fontSize: '13px', color: 'rgba(255,255,255,0.4)', fontStyle: 'italic', marginBottom: '12px' }}>{movie.title} · {movie.year}</p>`);
sec(`        <div style={{ display: 'flex', gap: '12px', alignItems: 'center' }}>`);
sec(`          <div style={{ display: 'flex', alignItems: 'baseline', gap: '4px' }}><span style={{ fontSize: '24px', fontWeight: 700, color: '#c9a86c', fontFamily: "'Playfair Display', serif" }}>{movie.rating}</span><span style={{ fontSize: '11px', color: 'rgba(255,255,255,0.3)' }}>/10</span></div>`);
sec(`          <ActionButtons id={movie.id} status={status} onToggle={onToggle} />`);
sec(`        </div>`);
sec(`      </div>`);
sec(`    </div>`);
sec(`  )`);
sec(`}`);
sec(``);
sec(`function MovieCard({ movie, status, onToggle, onClick }: { movie: Movie; status: WatchStatus; onToggle: (id: number, t: Exclude<WatchStatus, 'none'>) => void; onClick: () => void }) {`);
sec(`  return (`);
sec(`    <div style={{ borderRadius: '10px', overflow: 'hidden', cursor: 'pointer', background: '#111113', border: '1px solid #1e1e22', display: 'flex', flexDirection: 'column' }}>`);
sec(`      <div style={{ position: 'relative', paddingTop: '140%', background: '#1a1a1e' }}>`);
sec(`        <img src={imgUrl(movie.photo, 342)} alt={movie.titleCN} style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'cover' }} />`);
sec(`        <div style={{ position: 'absolute', top: '8px', right: '8px', background: 'rgba(0,0,0,0.65)', backdropFilter: 'blur(4px)', padding: '3px 8px', borderRadius: '6px', fontSize: '11px', fontWeight: 700, color: '#c9a86c' }}>★ {movie.rating}</div>`);
sec(`      </div>`);
sec(`      <div style={{ padding: '12px', display: 'flex', flexDirection: 'column', gap: '6px' }}>`);
sec(`        <h3 style={{ fontSize: '14px', fontWeight: 600, color: '#f0ece3', lineHeight: 1.2 }}>{movie.titleCN}</h3>`);
sec(`        <p style={{ fontSize: '11px', color: 'rgba(255,255,255,0.28)', fontStyle: 'italic' }}>{movie.title}</p>`);
sec(`        <div style={{ display: 'flex', gap: '4px', flexWrap: 'wrap' }}>{movie.genres.slice(0, 2).map(g => <GenreTag key={g} label={g} />)}</div>`);
sec(`        <div onClick={e => e.stopPropagation()}><ActionButtons id={movie.id} status={status[movie.id] ?? 'none'} onToggle={onToggle} compact /></div>`);
sec(`      </div>`);
sec(`    </div>`);
sec(`  )`);
sec(`}`);
sec(``);
sec(`function MyListItem({ movie, status, onToggle, onClick }: { movie: Movie; status: WatchStatus; onToggle: (id: number, t: Exclude<WatchStatus, 'none'>) => void; onClick: () => void }) {`);
sec(`  return (`);
sec(`    <div onClick={onClick} style={{ display: 'flex', gap: '16px', padding: '16px', borderRadius: '10px', background: '#111113', border: '1px solid #1e1e22', cursor: 'pointer' }}>`);
sec(`      <div style={{ width: '60px', height: '90px', borderRadius: '6px', overflow: 'hidden', flexShrink: 0, background: '#1a1a1e' }}>`);
sec(`        <img src={imgUrl(movie.photo, 185)} alt={movie.titleCN} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />`);
sec(`      </div>`);
sec(`      <div style={{ flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column', justifyContent: 'space-between', gap: '10px' }}>`);
sec(`        <div>`);
sec(`          <h3 style={{ fontFamily: "'Playfair Display', serif", fontSize: '16px', fontWeight: 600, color: '#f0ece3', marginBottom: '3px' }}>{movie.titleCN}</h3>`);
sec(`          <p style={{ fontSize: '11px', color: 'rgba(255,255,255,0.28)', fontStyle: 'italic', marginBottom: '8px' }}>{movie.title}</p>`);
sec(`          <div style={{ fontSize: '12px', color: 'rgba(255,255,255,0.38)', display: 'flex', gap: '10px', alignItems: 'center', marginBottom: '8px', flexWrap: 'wrap' }}>`);
sec(`            <span style={{ color: '#c9a86c', fontWeight: 700 }}>★ {movie.rating}</span>`);
sec(`            <span style={{ opacity: 0.3 }}>·</span><span>{movie.year}</span><span style={{ opacity: 0.3 }}>·</span><span>{movie.director || ''}</span>`);
sec(`          </div>`);
sec(`          <div style={{ display: 'flex', gap: '4px', flexWrap: 'wrap' }}>{movie.genres.map(g => <GenreTag key={g} label={g} />)}</div>`);
sec(`        </div>`);
sec(`        <ActionButtons id={movie.id} status={status} onToggle={onToggle} />`);
sec(`      </div>`);
sec(`    </div>`);
sec(`  )`);
sec(`}`);
sec(``);
sec(`function SimilarMovieRow({ movie, onClick }: { movie: Movie; onClick: () => void }) {`);
sec(`  return (`);
sec(`    <div onClick={onClick} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '14px 0', borderBottom: '1px solid rgba(255,255,255,0.05)', cursor: 'pointer', gap: '12px' }} onMouseEnter={e => (e.currentTarget.style.opacity = '0.7')} onMouseLeave={e => (e.currentTarget.style.opacity = '1')}>`);
sec(`      <div style={{ minWidth: 0 }}>`);
sec(`        <span style={{ fontFamily: "'Playfair Display', serif", fontSize: '15px', color: '#f0ece3', fontWeight: 500 }}>{movie.titleCN}</span>`);
sec(`        <span style={{ fontSize: '12px', color: 'rgba(255,255,255,0.32)', marginLeft: '8px' }}>{movie.year} · {movie.director}</span>`);
sec(`      </div>`);
sec(`      <div style={{ display: 'flex', alignItems: 'center', gap: '8px', flexShrink: 0 }}>`);
sec(`        {movie.genres.slice(0, 2).map(g => <GenreTag key={g} label={g} />)}`);
sec(`        <span style={{ color: '#c9a86c', fontWeight: 700, fontSize: '13px', minWidth: '36px', textAlign: 'right' }}>★ {movie.rating}</span>`);
sec(`        <span style={{ color: 'rgba(255,255,255,0.2)', fontSize: '14px' }}>›</span>`);
sec(`      </div>`);
sec(`    </div>`);
sec(`  )`);
sec(`}`);
sec(``);
sec(`function MovieDetail({ movie, status, onToggle, allMovies, onBack, onMovieClick }: { movie: Movie; status: WatchStatus; onToggle: (id: number, t: Exclude<WatchStatus, 'none'>) => void; allMovies: Movie[]; onBack: () => void; onMovieClick: (id: number) => void }) {`);
sec(`  const similar = allMovies.filter(m => m.id !== movie.id && m.genres.some(g => movie.genres.includes(g))).sort((a, b) => b.rating - a.rating).slice(0, 6)`);
sec(`  return (`);
sec(`    <div style={{ maxWidth: '800px', margin: '0 auto', padding: '0 24px 80px' }}>`);
sec(`      <div style={{ padding: '20px 0 0' }}>`);
sec(`        <button onClick={onBack} style={{ display: 'flex', alignItems: 'center', gap: '6px', background: 'none', border: 'none', color: 'rgba(255,255,255,0.4)', fontSize: '13px', cursor: 'pointer', padding: '6px 0', fontFamily: "'DM Sans', system-ui, sans-serif" }} onMouseEnter={e => (e.currentTarget.style.color = '#c9a86c')} onMouseLeave={e => (e.currentTarget.style.color = 'rgba(255,255,255,0.4)')}>← 返回</button>`);
sec(`      </div>`);
sec(`      <div style={{ position: 'relative', borderRadius: '12px', overflow: 'hidden', marginTop: '16px', height: 'clamp(260px, 40vw, 420px)', background: '#131315' }}>`);
sec(`        <img src={imgUrl(movie.backdrop || movie.photo, 1000)} alt={movie.titleCN} style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'cover', objectPosition: 'center 30%' }} />`);
sec(`        <div style={{ position: 'absolute', inset: 0, background: 'linear-gradient(to top, rgba(10,10,12,0.96) 0%, rgba(10,10,12,0.5) 50%, rgba(10,10,12,0.15) 100%)' }} />`);
sec(`        <div style={{ position: 'absolute', bottom: 0, left: 0, right: 0, padding: '28px 32px', zIndex: 1 }}>`);
sec(`          <div style={{ display: 'flex', gap: '6px', marginBottom: '10px', flexWrap: 'wrap' }}>{movie.genres.map(g => <GenreTag key={g} label={g} />)}</div>`);
sec(`          <h1 style={{ fontFamily: "'Playfair Display', serif", fontSize: 'clamp(24px, 4vw, 38px)', fontWeight: 700, color: '#f0ece3', lineHeight: 1.1, letterSpacing: '-0.02em', marginBottom: '4px' }}>{movie.titleCN}</h1>`);
sec(`          <p style={{ fontSize: '13px', color: 'rgba(255,255,255,0.35)', fontStyle: 'italic', letterSpacing: '0.03em' }}>{movie.title}</p>`);
sec(`        </div>`);
sec(`      </div>`);
sec(`      <div style={{ marginTop: '28px' }}>`);
sec(`        <div style={{ display: 'flex', alignItems: 'center', gap: '6px', flexWrap: 'wrap', marginBottom: '20px', padding: '16px 20px', borderRadius: '10px', background: '#111113', border: '1px solid rgba(255,255,255,0.05)' }}>`);
sec(`          <div style={{ display: 'flex', alignItems: 'baseline', gap: '4px', marginRight: '12px' }}><span style={{ fontSize: '28px', fontWeight: 700, color: '#c9a86c', fontFamily: "'Playfair Display', serif", lineHeight: 1 }}>{movie.rating}</span><span style={{ fontSize: '12px', color: 'rgba(255,255,255,0.3)', letterSpacing: '0.04em' }}>/10</span></div>`);
sec(`          <div style={{ width: '1px', height: '28px', background: 'rgba(255,255,255,0.08)', flexShrink: 0 }} />`);
sec(`          <div style={{ display: 'flex', gap: '20px', flexWrap: 'wrap', paddingLeft: '12px', fontSize: '13px', color: 'rgba(255,255,255,0.5)' }}>`);
sec(`            <div><div style={{ fontSize: '10px', letterSpacing: '0.08em', color: 'rgba(255,255,255,0.28)', marginBottom: '3px' }}>年份</div><div style={{ color: '#f0ece3', fontWeight: 500 }}>{movie.year}</div></div>`);
sec(`            <div><div style={{ fontSize: '10px', letterSpacing: '0.08em', color: 'rgba(255,255,255,0.28)', marginBottom: '3px' }}>时长</div><div style={{ color: '#f0ece3', fontWeight: 500 }}>{movie.duration} 分钟</div></div>`);
sec(`            <div><div style={{ fontSize: '10px', letterSpacing: '0.08em', color: 'rgba(255,255,255,0.28)', marginBottom: '3px' }}>导演</div><div style={{ color: '#f0ece3', fontWeight: 500 }}>{movie.director}</div></div>`);
sec(`          </div>`);
sec(`        </div>`);
sec(`        <div style={{ marginBottom: '28px' }}><ActionButtons id={movie.id} status={status} onToggle={onToggle} /></div>`);
sec(`        <div style={{ marginBottom: '40px' }}>`);
sec(`          <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '14px' }}>`);
sec(`            <h2 style={{ fontFamily: "'Playfair Display', serif", fontSize: '14px', fontWeight: 600, color: 'rgba(255,255,255,0.5)', letterSpacing: '0.1em', textTransform: 'uppercase' }}>剧情简介</h2>`);
sec(`            <div style={{ flex: 1, height: '1px', background: 'rgba(255,255,255,0.07)' }} />`);
sec(`          </div>`);
sec(`          <p style={{ fontSize: '15px', lineHeight: 1.8, color: 'rgba(255,255,255,0.65)' }}>{movie.description}</p>`);
sec(`        </div>`);
sec(`        {similar.length > 0 && (`);
sec(`          <div>`);
sec(`            <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '4px' }}>`);
sec(`              <h2 style={{ fontFamily: "'Playfair Display', serif", fontSize: '14px', fontWeight: 600, color: 'rgba(255,255,255,0.5)', letterSpacing: '0.1em', textTransform: 'uppercase' }}>相似推荐</h2>`);
sec(`              <div style={{ flex: 1, height: '1px', background: 'rgba(255,255,255,0.07)' }} />`);
sec(`            </div>`);
sec(`            <div>{similar.map(m => (<SimilarMovieRow key={m.id} movie={m} onClick={() => onMovieClick(m.id)} />))}</div>`);
sec(`          </div>`);
sec(`        )}`);
sec(`      </div>`);
sec(`    </div>`);
sec(`  )`);
sec(`}`);
sec(``);
sec(`function TrendingSection({ movies, status, onToggle, onMovieClick }: { movies: Movie[]; status: Record<number, WatchStatus>; onToggle: (id: number, t: Exclude<WatchStatus, 'none'>) => void; onMovieClick: (id: number) => void }) {`);
sec(`  return (`);
sec(`    <div style={{ marginTop: '48px' }}>`);
sec(`      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '16px' }}>`);
sec(`        <div>`);
sec(`          <p style={{ fontSize: '10px', letterSpacing: '0.16em', color: 'rgba(201,168,108,0.7)', fontFamily: "'Playfair Display', serif", fontWeight: 500, marginBottom: '6px' }}>TRENDING</p>`);
sec(`          <h2 style={{ fontFamily: "'Playfair Display', serif", fontSize: 'clamp(18px, 2.5vw, 24px)', fontWeight: 600, color: '#f0ece3' }}>近期热门</h2>`);
sec(`        </div>`);
sec(`        <div style={{ display: 'flex', gap: '4px', fontSize: '11px', color: 'rgba(255,255,255,0.25)', letterSpacing: '0.04em' }}><span>热门</span><span style={{ color: 'rgba(201,168,108,0.5)' }}>·</span><span>本周</span></div>`);
sec(`      </div>`);
sec(`      <div style={{ display: 'flex', gap: '14px', overflowX: 'auto', paddingBottom: '4px' }} className="hide-scrollbar">`);
sec(`        {movies.map(m => (`);
sec(`          <div key={m.id} onClick={() => onMovieClick(m.id)} style={{ flex: '0 0 clamp(160px, 26vw, 220px)', borderRadius: '10px', overflow: 'hidden', cursor: 'pointer', background: '#111113', border: '1px solid #1e1e22', display: 'flex', flexDirection: 'column' }}>`);
sec(`            <div style={{ position: 'relative', paddingTop: '140%', background: '#1a1a1e' }}>`);
sec(`              <img src={imgUrl(m.photo, 342)} alt={m.titleCN} style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'cover' }} />`);
sec(`              <div style={{ position: 'absolute', top: '8px', right: '8px', background: 'rgba(0,0,0,0.65)', backdropFilter: 'blur(4px)', padding: '3px 8px', borderRadius: '6px', fontSize: '11px', fontWeight: 700, color: '#c9a86c' }}>★ {m.rating}</div>`);
sec(`            </div>`);
sec(`            <div style={{ padding: '12px', display: 'flex', flexDirection: 'column', gap: '6px' }}>`);
sec(`              <h3 style={{ fontSize: '14px', fontWeight: 600, color: '#f0ece3', lineHeight: 1.2 }}>{m.titleCN}</h3>`);
sec(`              <p style={{ fontSize: '11px', color: 'rgba(255,255,255,0.28)', fontStyle: 'italic' }}>{m.title}</p>`);
sec(`              <div style={{ display: 'flex', gap: '4px', flexWrap: 'wrap' }}>{m.genres.slice(0, 2).map(g => <GenreTag key={g} label={g} />)}</div>`);
sec(`              <div onClick={e => e.stopPropagation()}><ActionButtons id={m.id} status={status[m.id] ?? 'none'} onToggle={onToggle} compact /></div>`);
sec(`            </div>`);
sec(`          </div>`);
sec(`        ))}`);
sec(`      </div>`);
sec(`    </div>`);
sec(`  )`);
sec(`}`);
console.log('Header + components done');
sec(``);
sec(`export default function App() {`);
sec(`  const [tab, setTab] = useState<'today' | 'mylist'>('today')`);
sec(`  const [selectedGenreId, setSelectedGenreId] = useState<number | null>(null)`);
sec(`  const [status, setStatus] = useState<Record<number, WatchStatus>>({})`);
sec(`  const [myFilter, setMyFilter] = useState<'want' | 'watched'>('want')`);
sec(`  const [selectedMovieId, setSelectedMovieId] = useState<number | null>(null)`);
sec(`  const [discoverPool, setDiscoverPool] = useState<Movie[]>([])`);
sec(`  const [trendingMovies, setTrendingMovies] = useState<Movie[]>([])`);
sec(`  const [genreList, setGenreList] = useState<{ id: number; name: string }[]>([])`);
sec(`  const [loading, setLoading] = useState(true)`);
sec(`  const [error, setError] = useState<string | null>(null)`);
sec(`  const [detailCache, setDetailCache] = useState<Record<number, Movie>>({})`);
sec(``);
sec(`  useEffect(() => { fetchGenres().then(g => setGenreList(g)).catch(() => {}) }, [])`);
sec(`  useEffect(() => {`);
sec(`    setLoading(true); setError(null)`);
sec(`    fetchDiscover({ genreId: selectedGenreId ?? undefined, sortBy: 'vote_average.desc', voteCountGte: 200, page: 1 })`);
sec(`      .then(r => { setDiscoverPool(r.map(tmdbToMovieMinimal)); setLoading(false) })`);
sec(`      .catch(e => { setError(e.message); setLoading(false) })`);
sec(`  }, [selectedGenreId])`);
sec(`  useEffect(() => { fetchTrending().then(r => setTrendingMovies(r.map(tmdbToMovieMinimal))).catch(() => {}) }, [])`);
sec(``);
sec(`  const allMovies = useMemo(() => [...discoverPool, ...trendingMovies], [discoverPool, trendingMovies])`);
sec(`  const dailyPicks = useMemo(() => getDailyPicks(discoverPool), [discoverPool])`);
sec(``);
sec(`  const toggleStatus = (id: number, target: Exclude<WatchStatus, 'none'>) => {`);
sec(`    setStatus(prev => ({ ...prev, [id]: prev[id] === target ? 'none' : target }))`);
sec(`  }`);
sec(``);
sec(`  const navigateToMovie = async (id: number) => {`);
sec(`    setSelectedMovieId(id)`);
sec(`    if (!detailCache[id]) {`);
sec(`      try {`);
sec(`        const detail = await fetchMovieDetail(id)`);
sec(`        const existing = allMovies.find(m => m.id === id)`);
sec(`        if (existing) setDetailCache(p => ({ ...p, [id]: enrichMovieWithDetail(existing, detail) }))`);
sec(`      } catch {}`);
sec(`    }`);
sec(`    window.scrollTo({ top: 0, behavior: 'smooth' })`);
sec(`  }`);
sec(``);
sec(`  const handleTabChange = (t: 'today' | 'mylist') => { setTab(t); setSelectedMovieId(null) }`);
sec(``);
sec(`  const wantList = allMovies.filter(m => status[m.id] === 'want')`);
sec(`  const watchedList = allMovies.filter(m => status[m.id] === 'watched')`);
sec(`  const myList = myFilter === 'want' ? wantList : watchedList`);
sec(`  const featured = dailyPicks[0]`);
sec(`  const rest = dailyPicks.slice(1)`);
sec(`  const selectedMovie = selectedMovieId !== null ? (detailCache[selectedMovieId] ?? allMovies.find(m => m.id === selectedMovieId) ?? null) : null`);
sec(``);
sec(`  return (`);
sec(`    <div style={{ minHeight: '100vh', background: '#0a0a0c', color: '#ede8df', fontFamily: "'DM Sans', system-ui, sans-serif" }}>`);
sec(`      <header style={{ position: 'sticky', top: 0, zIndex: 50, background: 'rgba(10,10,12,0.92)', backdropFilter: 'blur(16px)', WebkitBackdropFilter: 'blur(16px)', borderBottom: '1px solid rgba(255,255,255,0.06)', padding: '0 24px' }}>`);
sec(`        <div style={{ maxWidth: '1200px', margin: '0 auto', display: 'flex', alignItems: 'center', justifyContent: 'space-between', height: '58px', gap: '16px' }}>`);
sec(`          <div style={{ display: 'flex', alignItems: 'center', gap: '12px', flexShrink: 0 }}>`);
sec(`            <button onClick={() => { setSelectedMovieId(null); setTab('today') }} style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 0, display: 'flex', alignItems: 'center', gap: '12px' }}>`);
sec(`              <span style={{ fontFamily: "'Playfair Display', serif", fontSize: '21px', fontWeight: 700, color: '#f0ece3', letterSpacing: '0.03em' }}>REEL</span>`);
sec(`              <span style={{ fontSize: '10px', color: 'rgba(255,255,255,0.28)', borderLeft: '1px solid rgba(255,255,255,0.1)', paddingLeft: '12px', letterSpacing: '0.08em', fontWeight: 500 }}>每日好片</span>`);
sec(`            </button>`);
sec(`          </div>`);
sec(`          <div style={{ fontSize: '11px', color: 'rgba(255,255,255,0.28)', letterSpacing: '0.04em', textAlign: 'center', flexShrink: 0 }}>{getTodayString()}</div>`);
sec(`          <div style={{ display: 'flex', gap: '4px', alignItems: 'center', flexShrink: 0 }}>`);
sec(`            <button onClick={() => handleTabChange('mylist')} style={{ display: 'flex', alignItems: 'center', gap: '5px', padding: '5px 10px', borderRadius: '6px', background: 'none', border: 'none', cursor: 'pointer', color: wantList.length > 0 ? '#c9a86c' : 'rgba(255,255,255,0.28)', fontSize: '12px', fontFamily: "'DM Sans', system-ui, sans-serif" }}><span>♡</span><span style={{ fontWeight: 700 }}>{wantList.length}</span></button>`);
sec(`            <button onClick={() => handleTabChange('mylist')} style={{ display: 'flex', alignItems: 'center', gap: '5px', padding: '5px 10px', borderRadius: '6px', background: 'none', border: 'none', cursor: 'pointer', color: watchedList.length > 0 ? '#c9a86c' : 'rgba(255,255,255,0.28)', fontSize: '12px', fontFamily: "'DM Sans', system-ui, sans-serif" }}><span>●</span><span style={{ fontWeight: 700 }}>{watchedList.length}</span></button>`);
sec(`          </div>`);
sec(`        </div>`);
sec(`      </header>`);
sec(``);
sec(`      {!selectedMovie && (`);
sec(`        <div style={{ background: '#0a0a0c', borderBottom: '1px solid rgba(255,255,255,0.06)', padding: '0 24px' }}>`);
sec(`          <div style={{ maxWidth: '1200px', margin: '0 auto', display: 'flex' }}>`);
sec(`            {(['today', 'mylist'] as const).map(t => (`);
sec(`              <button key={t} onClick={() => handleTabChange(t)} style={{ padding: '13px 20px', fontSize: '13px', fontWeight: tab === t ? 600 : 400, color: tab === t ? '#f0ece3' : 'rgba(255,255,255,0.32)', background: 'none', border: 'none', borderBottom: tab === t ? '2px solid #c9a86c' : '2px solid transparent', cursor: 'pointer', letterSpacing: '0.02em', marginBottom: '-1px', fontFamily: "'DM Sans', system-ui, sans-serif" }}>`);
sec(`                {t === 'today' ? '今日推荐' : \`我的片单\${wantList.length + watchedList.length > 0 ? \` 路 \${wantList.length + watchedList.length}\` : ''}\`}`);
sec(`              </button>`);
sec(`            ))}`);
sec(`          </div>`);
sec(`        </div>`);
sec(`      )}`);
sec(``);
sec(`      {selectedMovie ? (`);
sec(`        <MovieDetail movie={selectedMovie} status={status[selectedMovie.id] ?? 'none'} onToggle={toggleStatus} allMovies={allMovies} onBack={() => setSelectedMovieId(null)} onMovieClick={navigateToMovie} />`);
sec(`      ) : (`);
sec(`        <main style={{ maxWidth: '1200px', margin: '0 auto', padding: '32px 24px 80px' }}>`);
sec(`          {tab === 'today' ? (`);
sec(`            <>{/* Quote section */}`);
sec(`              <div style={{ marginBottom: '32px', padding: '28px 24px', borderRadius: '10px', background: 'linear-gradient(135deg, rgba(201,168,108,0.08) 0%, rgba(201,168,108,0.02) 100%)', border: '1px solid rgba(201,168,108,0.12)' }}>`);
sec(`                <p style={{ fontFamily: "'Playfair Display', serif", fontStyle: 'italic', fontSize: '15px', lineHeight: 1.6, color: '#c9a86c', textAlign: 'center' }}>"{(function(){const q=getDailyQuote();return q.text})()}"</p>`);
sec(`                <p style={{ fontSize: '11px', color: 'rgba(255,255,255,0.28)', textAlign: 'center', marginTop: '10px' }}>—— {(function(){const q=getDailyQuote();return q.movie})()} ({getDailyQuote().year})</p>`);
sec(`              </div>`);
sec(`              <div className="hide-scrollbar" style={{ display: 'flex', gap: '8px', overflowX: 'auto', paddingBottom: '2px', marginBottom: '28px' }}>`);
sec(`                <button onClick={() => setSelectedGenreId(null)} style={{ padding: '7px 16px', borderRadius: '20px', fontSize: '13px', fontWeight: selectedGenreId === null ? 600 : 400, border: selectedGenreId === null ? '1px solid rgba(201,168,108,0.5)' : '1px solid rgba(255,255,255,0.08)', background: selectedGenreId === null ? 'rgba(201,168,108,0.1)' : 'transparent', color: selectedGenreId === null ? '#c9a86c' : 'rgba(255,255,255,0.4)', cursor: 'pointer', whiteSpace: 'nowrap', flexShrink: 0, fontFamily: "'DM Sans', system-ui, sans-serif" }}>全部</button>`);
sec(`                {genreList.map(g => (`);
sec(`                  <button key={g.id} onClick={() => setSelectedGenreId(g.id)} style={{ padding: '7px 16px', borderRadius: '20px', fontSize: '13px', fontWeight: selectedGenreId === g.id ? 600 : 400, border: selectedGenreId === g.id ? '1px solid rgba(201,168,108,0.5)' : '1px solid rgba(255,255,255,0.08)', background: selectedGenreId === g.id ? 'rgba(201,168,108,0.1)' : 'transparent', color: selectedGenreId === g.id ? '#c9a86c' : 'rgba(255,255,255,0.4)', cursor: 'pointer', whiteSpace: 'nowrap', flexShrink: 0, fontFamily: "'DM Sans', system-ui, sans-serif" }}>{g.name}</button>`);
sec(`                ))}`);
sec(`              </div>`);
sec(`              <div style={{ marginBottom: '20px' }}>`);
sec(`                <p style={{ fontSize: '10px', letterSpacing: '0.16em', color: 'rgba(201,168,108,0.7)', fontFamily: "'Playfair Display', serif", fontWeight: 500, marginBottom: '7px' }}>RECOMMENDED</p>`);
sec(`                <h1 style={{ fontFamily: "'Playfair Display', serif", fontSize: 'clamp(22px, 3vw, 30px)', fontWeight: 600, color: '#f0ece3', letterSpacing: '-0.02em', lineHeight: 1 }}>今日推荐</h1>`);
sec(`              </div>`);
sec(`              {loading ? (`);
sec(`                <div style={{ textAlign: 'center', padding: '100px 0', color: 'rgba(255,255,255,0.22)', fontSize: '14px' }}>加载中...</div>`);
sec(`              ) : error ? (`);
sec(`                <div style={{ textAlign: 'center', padding: '100px 0', color: '#e74c3c', fontSize: '14px' }}>加载失败: {error}</div>`);
sec(`              ) : dailyPicks.length === 0 ? (`);
sec(`                <div style={{ textAlign: 'center', padding: '100px 0', color: 'rgba(255,255,255,0.22)', fontSize: '14px' }}>该类型暂无电影</div>`);
sec(`              ) : (`);
sec(`                <>{featured && <FeaturedCard movie={featured} status={status[featured.id] ?? 'none'} onToggle={toggleStatus} onClick={() => navigateToMovie(featured.id)} />}`);
sec(`                  {rest.length > 0 && (`);
sec(`                    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(170px, 1fr))', gap: '14px', marginTop: '14px' }}>`);
sec(`                      {rest.map(m => <MovieCard key={m.id} movie={m} status={status[m.id] ?? 'none'} onToggle={toggleStatus} onClick={() => navigateToMovie(m.id)} />)}`);
sec(`                    </div>`);
sec(`                  )}`);
sec(`                </>`);
sec(`              )}`);
sec(`              <TrendingSection movies={trendingMovies} status={status} onToggle={toggleStatus} onMovieClick={navigateToMovie} />`);
sec(`            </>`);
sec(`          ) : (`);
sec(`            <>`);
sec(`              <div style={{ marginBottom: '24px' }}>`);
sec(`                <p style={{ fontSize: '10px', letterSpacing: '0.16em', color: 'rgba(201,168,108,0.7)', fontFamily: "'Playfair Display', serif", fontWeight: 500, marginBottom: '8px' }}>MY LIST</p>`);
sec(`                <h1 style={{ fontFamily: "'Playfair Display', serif", fontSize: 'clamp(22px, 3vw, 30px)', fontWeight: 600, color: '#f0ece3', letterSpacing: '-0.02em' }}>我的片单</h1>`);
sec(`              </div>`);
sec(`              <div style={{ display: 'flex', gap: '8px', marginBottom: '24px' }}>`);
sec(`                <button onClick={() => setMyFilter('want')} style={{ padding: '8px 20px', borderRadius: '8px', fontSize: '13px', fontWeight: myFilter === 'want' ? 600 : 400, border: myFilter === 'want' ? '1px solid rgba(201,168,108,0.35)' : '1px solid rgba(255,255,255,0.08)', background: myFilter === 'want' ? 'rgba(201,168,108,0.09)' : 'transparent', color: myFilter === 'want' ? '#c9a86c' : 'rgba(255,255,255,0.38)', cursor: 'pointer', fontFamily: "'DM Sans', system-ui, sans-serif" }}>♡ 想看{wantList.length > 0 ? \` (\${wantList.length})\` : ''}</button>`);
sec(`                <button onClick={() => setMyFilter('watched')} style={{ padding: '8px 20px', borderRadius: '8px', fontSize: '13px', fontWeight: myFilter === 'watched' ? 600 : 400, border: myFilter === 'watched' ? '1px solid rgba(201,168,108,0.35)' : '1px solid rgba(255,255,255,0.08)', background: myFilter === 'watched' ? 'rgba(201,168,108,0.09)' : 'transparent', color: myFilter === 'watched' ? '#c9a86c' : 'rgba(255,255,255,0.38)', cursor: 'pointer', fontFamily: "'DM Sans', system-ui, sans-serif" }}>● 看过{watchedList.length > 0 ? \` (\${watchedList.length})\` : ''}</button>`);
sec(`              </div>`);
sec(`              {myList.length === 0 ? (`);
sec(`                <div style={{ textAlign: 'center', padding: '80px 0', color: 'rgba(255,255,255,0.2)' }}>`);
sec(`                  <div style={{ fontSize: '40px', marginBottom: '14px', opacity: 0.25 }}>{myFilter === 'want' ? '♡' : '●'}</div>`);
sec(`                  <p style={{ fontSize: '14px', marginBottom: '6px' }}>还没有标记想看的电影</p>`);
sec(`                  <p style={{ fontSize: '12px', marginTop: '6px', opacity: 0.55 }}>在今天推荐中标记你感兴趣的电影</p>`);
sec(`                  <button onClick={() => handleTabChange('today')} style={{ marginTop: '20px', padding: '9px 20px', borderRadius: '20px', border: '1px solid rgba(201,168,108,0.3)', background: 'rgba(201,168,108,0.08)', color: '#c9a86c', fontSize: '13px', cursor: 'pointer', fontFamily: "'DM Sans', system-ui, sans-serif", fontWeight: 500 }}>去看今日推荐 →</button>`);
sec(`                </div>`);
sec(`              ) : (`);
sec(`                <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>`);
sec(`                  {myList.map(m => <MyListItem key={m.id} movie={m} status={status[m.id] ?? 'none'} onToggle={toggleStatus} onClick={() => navigateToMovie(m.id)} />)}`);
sec(`                </div>`);
sec(`              )}`);
sec(`            </>`);
sec(`          )}`);
sec(`        </main>`);
sec(`      )}`);
sec(`    </div>`);
sec(`  )`);
sec(`}`);
console.log('App component done');
